server:
  port: 81
spring:
  application:
    name: dataorgregister
  data:
    mongodb:
      uri: mongodb://10.0.82.3:27017/dataorg
  mail:
    default-encoding: utf-8
    host: mail.cstnet.cn
    port: 465
    username: casdc@cnic.cn
    password: Ruanjianzhan0802!@#
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true

publicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCYlVDsnkIM0bUwZfCDaeuPxaOo5pqvq79KL+bisvkzi01QM5OP5p3xPQ+hY928Cy4x9vgEGgia5au2Iz/hwA4CIXFe7WCNJrgQBPCPaZMxnMtCLr2Crgb2IIr+QSV/HKJA/skPYBobDPKyGswYKzm2sLLGo/ObiV3z1+ayy2dRzQIDAQAB
privateKey: MIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAJiVUOyeQgzRtTBl8INp64/Fo6jmmq+rv0ov5uKy+TOLTVAzk4/mnfE9D6Fj3bwLLjH2+AQaCJrlq7YjP+HADgIhcV7tYI0muBAE8I9pkzGcy0IuvYKuBvYgiv5BJX8cokD+yQ9gGhsM8rIazBgrObawssaj85uJXfPX5rLLZ1HNAgMBAAECgYBBmzo/c1CtGGJS3BINPzbVC8Lx9a2fSTan3G7nHNM/0W69xF93aU6SEpIs77bAiwIi47ECensmtwgc+Y0XMTAUGFyzu22k8URd66Ey4HGhKXjjpqEm3/pJ2y3scwitOCoWzm5dpWMicv0ek4NIiDBTKF/+Izdrhu31nM+2j8fSAQJBAOd5fjLXVKOhOdvXmVxcXfQWUDS9ulHniVwYcOCtlo+x1T/OxaqE7WttqLq1o07wgeiSIh9Ku3LRsLTqb1rdy00CQQCov/p0oA538Hqaqk3OBA439IT2rQitzXIBSk0MQqtWt+ecvE+Uj8GQ/UJsCRVSFu/btoJ1HEy/eZaOINqBg2CBAkEAmDP99EY8xD9eQR06HU4rBTWq1ZMvsW1yl5kGl+Xsi13en89BkEdJqgr4GJUY5e4lLZzxTOwh53TUIZHJWNFgPQJBAInA5fhsbEM2uS8m1QrXPrAo2J3x1MLkkitBdzIJ/op06AqHosMYsx/jzmQY6iGv/a+zBj4JkxE/dUqiwRy2nYECQQCXyvsjEnW91uGFgxBh/XkfKworGPI+bDckZlsM4bTKFSZjtUDOU7qdaQ4Lbw6mOpFWdV4cfY3UJO3+acsf3zn6

swagger2:
  enable: true